name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: demo-sales
          directory: dist
        env:
          VITE_API_URL: https://sales-management-api.retailer-sales.workers.dev/api
          VITE_LICENSE_KEY: ABC-123
          VITE_GOOGLE_CLIENT_ID: 938440224317-l5arlpo9r92palggdh22vu9o49k5fill.apps.googleusercontent.com
          VITE_APP_NAME: DemoSales
          VITE_SHOP_NAME: MARKETING FIRM
          VITE_SHOP_ACCOUNT_NO: 1212121212
          VITE_SHOP_IFSC: SBIN000341